spring.application.name=numo
spring.datasource.url=jdbc:postgresql://localhost:5432/numo_db
spring.datasource.username=admin
spring.datasource.password=12345q

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

